//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE__ANALYSIS
    {
        public int COD__ANALYSIS { get; set; }
        public Nullable<int> COD__TYPE_OF_ANALYSIS { get; set; }
        public string ANALYSIS { get; set; }
    
        public virtual CODE__TYPE_OF_ANALYSIS CODE__TYPE_OF_ANALYSIS { get; set; }
    }
}
