//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE__COMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODE__COMPANY()
        {
            this.CODE_STATION = new HashSet<CODE_STATION>();
        }
    
        public int COD__COMPANY { get; set; }
        public int COD_TYPE { get; set; }
        public string COMPANY { get; set; }
    
        public virtual CODE_TYPE_OF_COMPANY CODE_TYPE_OF_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODE_STATION> CODE_STATION { get; set; }
    }
}
