//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_OIL
    {
        public int COD_OIL { get; set; }
        public int COD_TYPEOIL { get; set; }
        public string OIL { get; set; }
    
        public virtual CODE_TYPE_OF_OIL CODE_TYPE_OF_OIL { get; set; }
    }
}
