//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_STATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODE_STATION()
        {
            this.MAIN_TAB = new HashSet<MAIN_TAB>();
        }
    
        public int COD_STATION { get; set; }
        public int COD_TYPE { get; set; }
        public int COD__COMPANY { get; set; }
        public string STATION { get; set; }
    
        public virtual CODE__COMPANY CODE__COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIN_TAB> MAIN_TAB { get; set; }
    }
}
