//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gas
    {
        public int ID { get; set; }
        public Nullable<int> PaperID { get; set; }
        public Nullable<int> Oil { get; set; }
        public Nullable<double> H2 { get; set; }
        public Nullable<double> O2 { get; set; }
        public Nullable<double> N2 { get; set; }
        public Nullable<double> CO { get; set; }
        public Nullable<double> CO2 { get; set; }
        public Nullable<double> CH4 { get; set; }
        public Nullable<double> C2H6 { get; set; }
        public Nullable<double> C2H4 { get; set; }
        public Nullable<double> C2H2 { get; set; }
        public Nullable<double> TOT { get; set; }
        public string KF { get; set; }
        public string TDCG { get; set; }
        public string TDCG_Codes { get; set; }
        public string Fault_Codes { get; set; }
        public string RECOMMENDATIONS { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
