//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIN_TAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAIN_TAB()
        {
            this.FURAN_OIL = new HashSet<FURAN_OIL>();
            this.Gases = new HashSet<GAS>();
            this.TRANSFORMER_OIL = new HashSet<TRANSFORMER_OIL>();
            this.TURBINE_OIL = new HashSet<TURBINE_OIL>();
        }
    
        public int ID { get; set; }
        public double IN_NO { get; set; }
        public System.DateTime IN_DATE { get; set; }
        public Nullable<double> OUT_NO { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public Nullable<int> TYPE__COMPANY { get; set; }
        public Nullable<int> COMPANY { get; set; }
        public Nullable<int> STATION { get; set; }
        public Nullable<int> TYPE_OIL { get; set; }
        public Nullable<int> OIL__ANALYSIS { get; set; }
        public string RESULTS { get; set; }
        public string RECOMMENDATIONS { get; set; }
        public Nullable<decimal> COAST { get; set; }
        public Nullable<int> laboratory { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual CODE_STATION CODE_STATION { get; set; }
        public virtual CODE_TYPE_OF_OIL CODE_TYPE_OF_OIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FURAN_OIL> FURAN_OIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAS> Gases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFORMER_OIL> TRANSFORMER_OIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURBINE_OIL> TURBINE_OIL { get; set; }
    }
}
