//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.IO;
    using System.Linq;

    public partial class DatabaseEntities : DbContext
    {


        private static DatabaseEntities context = null;
        public static DatabaseEntities Initiate()
        {
            var path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            path = Path.Combine(path, "CCL Labs");
            AppDomain.CurrentDomain.SetData("DataDirectory", path);
            Directory.CreateDirectory(path);
            var files = Directory.GetFiles(path).ToList();
            if (files.FindAll(e => e.Contains("Database")).Count < 2)
            {
                File.Copy("Database.mdf", Path.Combine(path, "Database.mdf"));
                File.Copy("Database_log.ldf", Path.Combine(path, "Database_log.ldf"));
            }
            if (context == null)
                context = new DatabaseEntities();
            return context;
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            context = null;
            //context.Turbines.Load();
            //context.Turbines.Local;
        }
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CODE__ANALYSIS> CODE__ANALYSIS { get; set; }
        public virtual DbSet<CODE__COMPANY> CODE__COMPANY { get; set; }
        public virtual DbSet<CODE__TYPE_OF_ANALYSIS> CODE__TYPE_OF_ANALYSIS { get; set; }
        public virtual DbSet<CODE_LAB> CODE_LAB { get; set; }
        public virtual DbSet<CODE_OIL> CODE_OIL { get; set; }
        public virtual DbSet<CODE_STATION> CODE_STATION { get; set; }
        public virtual DbSet<CODE_TYPE_OF_COMPANY> CODE_TYPE_OF_COMPANY { get; set; }
        public virtual DbSet<CODE_TYPE_OF_OIL> CODE_TYPE_OF_OIL { get; set; }
        public virtual DbSet<FURAN_OIL> FURAN_OIL { get; set; }
        public virtual DbSet<GAS> Gases { get; set; }
        public virtual DbSet<MAIN_TAB> MAIN_TAB { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRANSFORMER_OIL> TRANSFORMER_OIL { get; set; }
        public virtual DbSet<TURBINE_OIL> TURBINE_OIL { get; set; }
        public virtual DbSet<OIL_CODE> OIL_CODE { get; set; }
    }
}
