//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.Furans = new HashSet<Furan>();
            this.Gases = new HashSet<Gas>();
            this.Transformers = new HashSet<Transformer>();
            this.Turbines = new HashSet<Turbine>();
        }
    
        public int ID { get; set; }
        public double ImportNo { get; set; }
        public System.DateTime ImportDate { get; set; }
        public Nullable<double> ExportNo { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> CompanyType { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Station { get; set; }
        public Nullable<int> OilType { get; set; }
        public Nullable<int> OilAnalysisType { get; set; }
        public string Results { get; set; }
        public string Recommendations { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Lab { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Furan> Furans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gas> Gases { get; set; }
        public virtual OilType OilType1 { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transformer> Transformers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turbine> Turbines { get; set; }
    }
}
