//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL_Oil_Labs_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turbine
    {
        public int ID { get; set; }
        public Nullable<int> PaperID { get; set; }
        public Nullable<double> SG { get; set; }
        public Nullable<double> KV { get; set; }
        public Nullable<double> FO { get; set; }
        public Nullable<double> WR { get; set; }
        public Nullable<double> COL { get; set; }
        public Nullable<double> TA { get; set; }
        public Nullable<double> IMP { get; set; }
        public Nullable<double> DN { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> PS { get; set; }
        public Nullable<int> Oil { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
